"""
Smart Money Concepts (SMC) Engine for ORB Scanner & Intraday Trading.

Implements two core institutional trading models:
1. Fair Value Gap (FVG) + Liquidity Sweep Strategy (Sweep & Reversal / Pullback)
2. Hidden Liquidity Retest Strategy (Breakout & Origin Candle Retest)

Supports:
- Index Futures & Options (Nifty 50, BankNifty, Sensex)
- NSE Equity Universe
- MCX Commodities (Crude Oil, Gold, Silver)
- 5m & 15m timeframes
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional, Tuple

from app.config import logger
from app.storage.models import Candle, Direction


@dataclass
class FairValueGap:
    """Represents a 3-candle Fair Value Gap (Imbalance / Liquidity Void)."""
    candle_idx: int
    timestamp: datetime
    direction: Direction
    top: float          # Upper boundary of the gap
    bottom: float       # Lower boundary of the gap
    midpoint: float     # 50% equilibrium entry level
    size: float         # Gap height in points
    is_mitigated: bool = False
    mitigated_at: Optional[datetime] = None


@dataclass
class LiquiditySweep:
    """Represents a sweep of previous swing highs or lows."""
    candle_idx: int
    timestamp: datetime
    direction: Direction
    swept_level: float
    extreme_price: float  # High/low reached during the sweep (Stop Loss level)
    wick_ratio: float
    confirmed: bool = True


@dataclass
class SMCOriginCandle:
    """Origin candle that initiated the displacement and breakout."""
    candle_idx: int
    timestamp: datetime
    direction: Direction
    open_price: float
    high: float
    low: float
    close_price: float
    retest_level: float  # High of origin for LONG, Low of origin for SHORT


@dataclass
class SMCTradeSetup:
    """Complete actionable setup generated by SMC strategies."""
    strategy_name: str   # 'FVG_SWEEP' or 'HIDDEN_LIQUIDITY'
    symbol: str
    direction: Direction
    setup_time: datetime
    entry_price: float
    stop_loss: float
    target_price: float
    risk_reward: float
    fvg: Optional[FairValueGap] = None
    sweep: Optional[LiquiditySweep] = None
    origin: Optional[SMCOriginCandle] = None
    status: str = "PENDING"  # PENDING, FILLED, TARGET_HIT, STOP_HIT, EXPIRED


class SMCEngine:
    """Analyzes candlestick series for institutional SMC signatures."""

    @staticmethod
    def detect_fvg(candles: List[Candle]) -> List[FairValueGap]:
        """
        Detects 3-candle Fair Value Gaps across a sequence of candles.
        - Bullish FVG: Candle 3 Low > Candle 1 High.
        - Bearish FVG: Candle 3 High < Candle 1 Low.
        """
        fvgs: List[FairValueGap] = []
        if len(candles) < 3:
            return fvgs

        for i in range(len(candles) - 2):
            c1 = candles[i]
            c2 = candles[i + 1]
            c3 = candles[i + 2]

            # Bullish FVG (Strong displacement up on c2)
            if c3.low > c1.high and c2.close > c2.open:
                gap_size = c3.low - c1.high
                midpoint = round((c1.high + c3.low) / 2.0, 2)
                fvgs.append(FairValueGap(
                    candle_idx=i + 1,
                    timestamp=c2.timestamp,
                    direction=Direction.LONG,
                    top=c3.low,
                    bottom=c1.high,
                    midpoint=midpoint,
                    size=round(gap_size, 2),
                ))

            # Bearish FVG (Strong displacement down on c2)
            elif c3.high < c1.low and c2.close < c2.open:
                gap_size = c1.low - c3.high
                midpoint = round((c1.low + c3.high) / 2.0, 2)
                fvgs.append(FairValueGap(
                    candle_idx=i + 1,
                    timestamp=c2.timestamp,
                    direction=Direction.SHORT,
                    top=c1.low,
                    bottom=c3.high,
                    midpoint=midpoint,
                    size=round(gap_size, 2),
                ))

        return fvgs

    @staticmethod
    def detect_liquidity_sweep(
        current_candle: Candle,
        swing_high: float,
        swing_low: float,
    ) -> Optional[LiquiditySweep]:
        """
        Identifies if current candle swept liquidity beyond a swing level
        and closed back inside (wick rejection).
        """
        c_range = current_candle.high - current_candle.low
        if c_range <= 0.0001:
            return None

        # Bearish Sweep of Swing High
        if current_candle.high > swing_high and current_candle.close < swing_high:
            upper_wick = (current_candle.high - max(current_candle.open, current_candle.close)) / c_range
            if upper_wick >= 0.28:
                return LiquiditySweep(
                    candle_idx=0,
                    timestamp=current_candle.timestamp,
                    direction=Direction.SHORT,
                    swept_level=swing_high,
                    extreme_price=current_candle.high,
                    wick_ratio=round(upper_wick, 3),
                )

        # Bullish Sweep of Swing Low
        if current_candle.low < swing_low and current_candle.close > swing_low:
            lower_wick = (min(current_candle.open, current_candle.close) - current_candle.low) / c_range
            if lower_wick >= 0.28:
                return LiquiditySweep(
                    candle_idx=0,
                    timestamp=current_candle.timestamp,
                    direction=Direction.LONG,
                    swept_level=swing_low,
                    extreme_price=current_candle.low,
                    wick_ratio=round(lower_wick, 3),
                )

        return None

    @staticmethod
    def is_displacement(candle: Candle, avg_volume: Optional[float] = None) -> bool:
        """
        Checks if candle represents institutional displacement:
        - Body ratio >= 60% of total candle range
        - Volume expansion if volume data available
        """
        c_range = candle.high - candle.low
        if c_range <= 0.0001:
            return False

        body = abs(candle.close - candle.open)
        body_ratio = body / c_range

        if body_ratio < 0.60:
            return False

        if avg_volume and avg_volume > 0:
            return (candle.volume / avg_volume) >= 1.3

        return True

    def evaluate_fvg_strategy(
        self,
        symbol: str,
        candles: List[Candle],
        swing_high: float,
        swing_low: float,
        risk_reward_target: float = 2.0,
        strict_filters: bool = True,
    ) -> Optional[SMCTradeSetup]:
        """
        Strategy 1: Fair Value Gap Sweep & Reversal / Pullback.
        1. Liquidity sweep of earlier high/low
        2. Displacement movement creating a structure break (body >= 60-65%)
        3. No large counter-wick rejection (opp wick <= 25%)
        4. FVG formed in displacement move
        5. Entry at 50% midpoint of the FVG
        6. Stop loss beyond sweep extreme
        7. Target: 2R
        """
        if len(candles) < 4:
            return None

        recent = candles[-1]
        sweep = self.detect_liquidity_sweep(recent, swing_high, swing_low)
        fvgs = self.detect_fvg(candles[-5:])

        if not fvgs:
            return None

        latest_fvg = fvgs[-1]

        # Strict Filter 1: Check displacement candle anatomy
        fvg_candle = candles[min(len(candles) - 1, latest_fvg.candle_idx + 1)] if latest_fvg.candle_idx < len(candles) else recent
        c_range = fvg_candle.high - fvg_candle.low
        if strict_filters and c_range > 0.0001:
            body_ratio = abs(fvg_candle.close - fvg_candle.open) / c_range
            upper_wick = (fvg_candle.high - max(fvg_candle.open, fvg_candle.close)) / c_range
            lower_wick = (min(fvg_candle.open, fvg_candle.close) - fvg_candle.low) / c_range

            # Require solid body (>= 60%) to prove institutional conviction
            if body_ratio < 0.60:
                return None

            # Trap filter: reject if counter-wick exceeds 28%
            if latest_fvg.direction == Direction.LONG and upper_wick > 0.28:
                return None
            elif latest_fvg.direction == Direction.SHORT and lower_wick > 0.28:
                return None

        # Bullish Setup
        if latest_fvg.direction == Direction.LONG:
            entry_p = latest_fvg.midpoint
            sl_p = swing_low if sweep is None else sweep.extreme_price
            if entry_p <= sl_p:
                return None
            risk = entry_p - sl_p
            target_p = round(entry_p + risk * risk_reward_target, 2)
            return SMCTradeSetup(
                strategy_name="FVG_SWEEP",
                symbol=symbol,
                direction=Direction.LONG,
                setup_time=latest_fvg.timestamp,
                entry_price=entry_p,
                stop_loss=round(sl_p, 2),
                target_price=target_p,
                risk_reward=risk_reward_target,
                fvg=latest_fvg,
                sweep=sweep,
            )

        # Bearish Setup
        elif latest_fvg.direction == Direction.SHORT:
            entry_p = latest_fvg.midpoint
            sl_p = swing_high if sweep is None else sweep.extreme_price
            if entry_p >= sl_p:
                return None
            risk = sl_p - entry_p
            target_p = round(entry_p - risk * risk_reward_target, 2)
            return SMCTradeSetup(
                strategy_name="FVG_SWEEP",
                symbol=symbol,
                direction=Direction.SHORT,
                setup_time=latest_fvg.timestamp,
                entry_price=entry_p,
                stop_loss=round(sl_p, 2),
                target_price=target_p,
                risk_reward=risk_reward_target,
                fvg=latest_fvg,
                sweep=sweep,
            )

        return None

    def evaluate_hidden_liquidity_strategy(
        self,
        symbol: str,
        candles: List[Candle],
        swing_high: float,
        swing_low: float,
        risk_reward_target: float = 2.0,
    ) -> Optional[SMCTradeSetup]:
        """
        Strategy 2: Hidden Liquidity Retest (Origin Candle Retest).
        1. Price breaks earlier high / low with displacement
        2. Identify origin candle that started the move
        3. Entry at origin candle High (for Long) or Low (for Short)
        4. Stop loss below/above swing low/high
        5. Target: 2R to 3R
        """
        if len(candles) < 4:
            return None

        # Look back 2-4 candles to find the breakout / displacement
        breakout_idx = None
        direction = None
        for i in range(len(candles) - 3, len(candles)):
            c = candles[i]
            if c.close > swing_high and self.is_displacement(c):
                breakout_idx = i
                direction = Direction.LONG
                break
            elif c.close < swing_low and self.is_displacement(c):
                breakout_idx = i
                direction = Direction.SHORT
                break

        if breakout_idx is None or direction is None or breakout_idx == 0:
            return None

        # Origin candle is the candle directly preceding the displacement move
        origin_candle = candles[breakout_idx - 1]

        if direction == Direction.LONG:
            entry_p = origin_candle.high
            sl_p = min(origin_candle.low, swing_low)
            if entry_p <= sl_p:
                return None
            risk = entry_p - sl_p
            target_p = round(entry_p + risk * risk_reward_target, 2)
            origin_info = SMCOriginCandle(
                candle_idx=breakout_idx - 1,
                timestamp=origin_candle.timestamp,
                direction=Direction.LONG,
                open_price=origin_candle.open,
                high=origin_candle.high,
                low=origin_candle.low,
                close_price=origin_candle.close,
                retest_level=entry_p,
            )
            return SMCTradeSetup(
                strategy_name="HIDDEN_LIQUIDITY",
                symbol=symbol,
                direction=Direction.LONG,
                setup_time=origin_candle.timestamp,
                entry_price=entry_p,
                stop_loss=round(sl_p, 2),
                target_price=target_p,
                risk_reward=risk_reward_target,
                origin=origin_info,
            )
        else:
            entry_p = origin_candle.low
            sl_p = max(origin_candle.high, swing_high)
            if entry_p >= sl_p:
                return None
            risk = sl_p - entry_p
            target_p = round(entry_p - risk * risk_reward_target, 2)
            origin_info = SMCOriginCandle(
                candle_idx=breakout_idx - 1,
                timestamp=origin_candle.timestamp,
                direction=Direction.SHORT,
                open_price=origin_candle.open,
                high=origin_candle.high,
                low=origin_candle.low,
                close_price=origin_candle.close,
                retest_level=entry_p,
            )
            return SMCTradeSetup(
                strategy_name="HIDDEN_LIQUIDITY",
                symbol=symbol,
                direction=Direction.SHORT,
                setup_time=origin_candle.timestamp,
                entry_price=entry_p,
                stop_loss=round(sl_p, 2),
                target_price=target_p,
                risk_reward=risk_reward_target,
                origin=origin_info,
            )


smc_engine = SMCEngine()
